name: ci

on:
  push:
    branches: ['v1.2.0']
    paths: ['**.ts', '**.js', '**.json', '**.yml']

  pull_request:
    branches: ['v1.2.0']
    paths: ['**.ts', '**.js', '**.json', '**.yml']
    types: [opened, synchronize, reopened]

jobs:
  check-dist:
    uses: ./.github/workflows/check-dist.yml

  build-latest:
    needs: [check-dist]
    uses: ./.github/workflows/setup-latest.yml

  setup-latest:
    needs: [check-dist]
    uses: ./.github/workflows/setup-latest.yml

  setup-legacy:
    needs: [check-dist]
    uses: ./.github/workflows/setup-legacy.yml

  setup-libraries:
    needs: [check-dist]
    uses: ./.github/workflows/setup-libraries.yml

  release:
    if: ${{ github.event_name == 'push' }}
    needs:
      [check-dist, build-latest, setup-latest, setup-legacy, setup-libraries]
    uses: ./.github/workflows/release.yml
